### PR TITLE
Add Initial DB initalisation + Optional do not import default data

### PR DESCRIPTION
**Pull request by J-Ha**
when Application gets started for first time, the artisan is not able to create the data, because the DB is completely empty.
first do a fresh migration to create all needed tables, before importing data.

additional created a flag to skip the import of default data, without impact if the variable is not set.

### CODE REVIEW

**Comment by karlomikus** [comment]
Thanks for this,
In version 3 `bar:open` command will be removed and you will be able to create multiple bars through the api, so this will not be needed.

**Comment by J-Ha** [comment]
at the moment it is not possible to launch a fresh barassistant/saltrim plattform with the given docker documentation.

the bar:open tries to create the admin user with the admin-password in the user table, that does not exist initially.
should maybe considered to release a v2.5.x version, as interims solution.

**Comment by karlomikus** [comment]
Oh yeah, I made a mistake in https://github.com/karlomikus/bar-assistant/commit/d5f275d9133e95ec0d04806d0ef4841736042ef5

**Comment by J-Ha** [comment]
yes, you may need to do the initial migration before bar:open.
but also on every boot, for update version coverage

**Pull request merged**
